### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Cmod777** [slaninas/tostr#2]
Followed instructions from command line, don't understand how to check if it works. To continue and see if can interact with the bot how do i do it? Need simplified instructions

**Comment by slaninas** [comment]
What happened when you run `build_and_run.sh`? You should see log in the terminal. After starting, the bot sends the hello message to the relays specified at the bottom of the `config` file. Assuming you have a nostr client connected to the same relay(s) that is the bot using, you should be able to find the bot's account using the pubkey corresponding to the private key you put into the `config`.

**Comment by cyborr** [comment]
Hi, I am running the bot, it is working but when try to get the messages from twitter accounts obtain this message 
CRITICAL:root:twint.run:Twint:Feed:noData'data'

**Comment by slaninas** [comment]
> Hi, I am running the bot, it is working but when try to get the messages from twitter accounts obtain this message CRITICAL:root:twint.run:Twint:Feed:noData'data'

Hi, yep, it uses [twint](https://github.com/twintproject/twint) which stopped working. I will try to make the bot work again when I have time.

**Comment by cyborr** [comment]
Thanks.

**Comment by slaninas** [comment]
I fixed one issue just to find out Elon just turned on login only mode, lol. So it's not working and I will archive this repo and won't spend more time on this anymore.
